__include__:
  [
    "../dataset/license_plate.yml",
    "../runtime.yml",
    "./include/dataloader.yml",
    "./include/optimizer.yml",
    "./include/rtdetrv2_r50vd.yml",
  ]

output_dir: ./output/license_plate
summary_dir: ./output/license_plate/tensorboard

PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True

HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5

RTDETRTransformerv2:
  num_layers: 3

epoches: 50

train_dataloader:
  total_batch_size: 8
  dataset:
    transforms:
      policy:
        epoch: 47
  collate_fn:
    scales: ~