__include__: [
  '../dataset/license_plate.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]

output_dir: /kaggle/working/output/rtdetrv2_r34vd_license_plate_smoke_tests

num_classes: 1
remap_mscoco_category: False

PResNet:
  depth: 34
  freeze_at: -1
  freeze_norm: False
  pretrained: True

epoches: 1
use_amp: False
use_ema: False

train_dataloader:
  dataset:
    img_folder: /kaggle/input/datasets/aungkhantbwar/baseline-test/baseline_test/images
    ann_file: /kaggle/input/datasets/aungkhantbwar/baseline-test/baseline_test/annotations/annotations.json
  total_batch_size: 1
  num_workers: 0

val_dataloader:
  dataset:
    img_folder: /kaggle/input/datasets/aungkhantbwar/baseline-test/baseline_test/images
    ann_file: /kaggle/input/datasets/aungkhantbwar/baseline-test/baseline_test/annotations/annotations.json
  total_batch_size: 1
  num_workers: 0